version: '3.2'
services:
  nginx-php:
    image: registry.cn-shenzhen.aliyuncs.com/yuanjm/nginx-php:v1
    container_name: nginx-php
    links:
      - mysql:mysql
    ports:
      - "80:80"
    volumes:
      - ./app:/data/wwwroot:rw
      - ./logs:/data/wwwlogs:rw
      - ./conf/nginx/vhost:/usr/local/nginx/conf/vhost:ro
      - ./conf/nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - ./conf/php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf:ro
      - ./work/nginx-php.sh:/opt/my.sh
    restart: always
    depends_on:
      - mysql
    command: bash -c "/opt/my.sh && /usr/bin/supervisord"

  mysql:
    restart: always
    image: mysql:5.6.45
    container_name: mysql5.6
    ports:
      - "33066:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    volumes:
      - ./data/mysql:/var/lib/mysql 
      - ./conf/mysql:/etc/mysql/conf.d:rw
      - ./logs/mysql:/var/log/mysql:rw
      - ./work/mysql.sh:/opt/my.sh
   
