version: '3.2'
services:
  dnp:
    image: registry.cn-shenzhen.aliyuncs.com/yuanjm/yuanjm:v1
    container_name: nginx-php
    ports:
      - "127.0.0.1:8080:80"
      - "192.168.1.69:8080:80"
    volumes:
      -  /data/wwwroot:/data/wwwroot:rw
      - ./logs:/data/wwwlogs:rw
      - ./conf/nginx/vhost:/usr/local/nginx/conf/vhost:ro
      - ./my.sh:/opt/my.sh:ro
    restart: always
    command: bash -c "/usr/bin/supervisord && /opt/my.sh"
